version: "3.9"

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: fileup_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "54327:5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_HOST: db
      DB_NAME: fileup_development
      DB_USERNAME: rails
      DB_PASSWORD: qwerty
      DB_PORT: 5432
    volumes:
      - .:/app
      - rails_cache:/app/tmp/cache
      - rails_storage:/app/storage
    ports:
      - "3007:3000"
    depends_on:
      - db

volumes:
  db_data:
  rails_cache:
  rails_storage:
